### ISSUE TITLE
BioSTEAM process simulation

### ISSUE THREAD

**Issue by yoelcortes** [Igben-Nehemiah/process-simulation#2]
Hi Igben,

I hope you are doing well! This is not an actual issue. I just ran into this repo by chance and I thought you might be interested in BioSTEAM. A well-established, open-source process simulator in Python with detailed documentation on how to extend the thermodynamic and unit operation modules:

https://biosteam.readthedocs.io/en/latest/

I hope this is useful. Feel free to close this issue once you see it.
Thanks!

**Comment by Igben-Nehemiah** [comment]
Thank you @yoelcortes, I'll do well to look at the BioSTEAM repository.
